version: '3.8'

services:
  web-django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - pgdb
  
  pgdb:
      image: postgres
      container_name: pgdb
      environment:
             - POSTGRES_DB=docker_db
             - POSTGRES_USER=postgres
             - POSTGRES_PASSWORD=nodejs12
      volumes:
             - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata:
